# ShadowText - Offline Text Steganography for Android

## Project Properties
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

## Android
android.useAndroidX=true
android.nonTransitiveRClass=true

## Kotlin
kotlin.code.style=official
kotlin.daemon.jvmargs=-Xmx1536m

## Version
SHADOW_TEXT_VERSION_NAME=1.0.0-alpha
SHADOW_TEXT_VERSION_CODE=1
SHADOW_TEXT_MIN_SDK=24
SHADOW_TEXT_TARGET_SDK=34
SHADOW_TEXT_COMPILE_SDK=34
